# Generated by Django 3.2.4 on 2021-06-22 14:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tutorial_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('english', models.CharField(blank=True, default='', max_length=250)),
                ('russian', models.CharField(blank=True, default='', max_length=250)),
                ('turkmen', models.CharField(blank=True, default='', max_length=250)),
                ('turkish', models.CharField(blank=True, default='', max_length=250)),
                ('color', models.CharField(blank=True, default='', max_length=250)),
            ],
            options={
                'ordering': ('english',),
            },
        ),
        migrations.DeleteModel(
            name='Language',
        ),
    ]
